sylius_grid:
    grids:
        grid_admin_role:
            driver:
                name: doctrine/orm
                options:
                    class: %sylius.model.role.class%

            sorting:
                left: asc

            fields:
                code:
                    type: string
                    label: sylius.ui.code
                name:
                    type: xtemplate
                    label: sylius.ui.name
                    path: .
                    options:
                        tpl: '<span style="padding-left:{{ data.level*20 }}px">{{ data.name }}</span>'
                description:
                    type: string
                    label: sylius.ui.description
                    options:
                        flex: 1

            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
