sylius_grid:
    grids:
        grid_admin_customer:
            driver:
                name: doctrine/orm
                options:
                    class: %sylius.model.customer.class%
            sorting:
                id: asc
                firstName: asc
                lastName: asc
                email: asc
                createdAt: asc

            fields:
                id:
                    type: string
                    label: ID
                firstName:
                    type: string
                    label: sylius.ui.first_name
                lastName:
                    type: string
                    label: sylius.ui.last_name
                email:
                    type: twig
                    label: sylius.ui.email
                    path: .
                    options:
                        flex: 1
                        template: IntbizthAdminBundle:Customer/Grid/Column:email.html.twig
                createdAt:
                    type: localizeddate
                    label: sylius.ui.registration_date
                enabled:
                    type: yesno
                    label: sylius.ui.confirmation
                    path: user.enabled
                    options:
                        align: 'center'
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
